version: "3.3"
services:
  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    container_name: ddiem-virtuoso
    environment:
      DBA_PASSWORD: "ABC"
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://ddiem.phenomebrowser.net"
    volumes:
      - ~/data/virtuoso:/data
    ports:
      - "8890:8890"
      - "1111:1111"
    restart: unless-stopped
    